# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jiscode', models.CharField(max_length=10, verbose_name='JIS X0401/X0402')),
                ('name', models.CharField(max_length=150)),
                ('kana', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'City',
            },
        ),
        migrations.CreateModel(
            name='JpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jiscode', models.CharField(max_length=10, verbose_name='JIS X0401/X0402')),
                ('zipcode5', models.CharField(max_length=5)),
                ('zipcode', models.CharField(max_length=7)),
                ('pref_kana', models.CharField(max_length=50)),
                ('city_kana', models.CharField(max_length=100)),
                ('town_kana', models.CharField(max_length=100)),
                ('pref_name', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=150)),
                ('town_name', models.CharField(max_length=150)),
                ('is_split', models.BooleanField()),
                ('is_small', models.BooleanField()),
                ('is_towncode', models.BooleanField()),
                ('is_multi', models.BooleanField()),
                ('is_changed', models.IntegerField()),
                ('reason', models.IntegerField()),
                ('city', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_jp.City')),
            ],
            options={
                'verbose_name': 'JP Address',
                'verbose_name_plural': 'JP Address',
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('slug', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('kana', models.CharField(db_index=True, max_length=50)),
                ('shortname', models.CharField(max_length=50)),
                ('jpaddress_url', models.URLField(blank=True, default=None, null=True)),
                ('neighbors', models.ManyToManyField(blank=True, related_name='_prefecture_neighbors_+', to='locations_jp.Prefecture')),
            ],
            options={
                'verbose_name': 'Prefecture',
                'verbose_name_plural': 'Prefectures',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='prefecture',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_jp.Region'),
        ),
        migrations.AddField(
            model_name='city',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations_jp.Prefecture'),
        ),
    ]
