# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_jp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpaddress',
            name='zipcode',
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='jpaddressimport',
            name='zipcode',
            field=models.CharField(db_index=True, max_length=7),
        ),
    ]
